# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8579b8eed4155285e62d0ec6f5c6be8aee8d59f467bc5c78ddb6073788ffb7fc2fe5e857360a433ca886190e386d0e972d21370258c7958667d51451a1f9956b

test:
  secret_key_base: a4af6f2eba8495eb7853f304879cae525cc5a572dadd265cd01ad1c777456cb8f7cd31d7134845d4a727e7b7ee1e3e82566433a211518619864366fde92fed21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
